#!/usr/bin/env bash

# Hook to make sure that no commit message line exceeds 72 characters

while read line; do
    # Skip comments
    if [ "${line:0:1}" == "#" ]; then
        continue
    fi
    if [ ${#line} -ge 73 ]; then
        echo -e "\e[1;31mCommit messages are limited to 72 characters.\e[0m"
        echo -e "\e[1;31mThe following commit message has ${#line} characters.\e[0m"
        echo "${line}"
        exit 1
    fi
done < "${1}"

exit 0
