#!/usr/bin/env bash

# Disk information to be shown as i3block

# Output 1 to 4 lines:
# 1) full_text
# 2) short_text
# 3) color
# 4) background

green=#00FF00
yellow=#FFF600
orange=#FFAE00
red=#FF0000

dfh=$(df -h | awk '/home$/ {print($4)}')
df=$(df | awk '/home$/ {print($4)}')

# Echo full text
echo "D: ${dfh}"

# Echo short text
echo "${df}"

# Echo color
if [ ${df} -ge 3000000 ]; then
    echo "${green}"
elif [ ${df} -ge 2000000 ]; then
    echo "${yellow}"
elif [ ${df} -ge 1000000 ]; then
    echo "${orange}"
elif [ ${df} -ge 500000 ]; then
    echo "${red}"
else
    echo "${green}"
    echo "${red}"
fi
