#!/usr/bin/env bash

# Network information to be shown as i3block

# Output 1 to 4 lines:
# 1) full_text
# 2) short_text
# 3) color
# 4) background

# See:
# https://i3wm.org/docs/i3bar-protocol.html#_blocks_in_detail
# https://github.com/vivien/i3blocks

green=#00FF00
yellow=#FFF600
orange=#FFAE00
red=#FF0000

# Get connection information
ip4E=$(curl -s 'https://api.ipify.org')

# Check if we really got an IP
if [[ "${ip4E}" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]] ; then
    # Echo full text
    echo "I: ${ip4E}"
else
    echo "I: ?"
fi

# Echo short text
echo ""
