#!/usr/bin/env bash

# Network information to be shown as i3block

# Output 1 to 4 lines:
# 1) full_text
# 2) short_text
# 3) color
# 4) background

# See:
# https://i3wm.org/docs/i3bar-protocol.html#_blocks_in_detail
# https://github.com/vivien/i3blocks

green=#00FF00
yellow=#FFF600
orange=#FFAE00
red=#FF0000

# Echo full text
awk '{print("L:", $1, $2, $3)}' < /proc/loadavg

# Echo short text
awk '{print("L:", $1, $2, $3)}' < /proc/loadavg

# Echo color
loadavg1mx100=$(awk '{print(100*$1)}' < /proc/loadavg)
if [ "${loadavg1mx100}" -le 200 ]; then
    echo "${green}"
elif [ "${loadavg1mx100}" -le 300 ]; then
    echo "${yellow}"
elif [ "${loadavg1mx100}" -le 400 ]; then
    echo "${orange}"
else
    echo "${red}"
fi
